export const ACTION_TYPE = {
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
  SET_PRODUCTS_DATA: "SET_PRODUCTS_DATA",
  SET_CATEGORIES_DATA: "SET_CATEGORIES_DATA",
  SET_CART_DATA: "SET_CART_DATA",
};
